version: 2

models:
  - name: customer
    columns:
      - name: C_CUSTKEY
        description: "customer reference information"
        tests:
          - unique
          - not_null

  - name: part
    columns:
      - name: P_PARTKEY
        description: "part reference information"
        tests:
          - unique
          - not_null

  - name: supplier
    columns:
      - name: S_SUPPKEY
        description: "supplier reference information"
        tests:
          - unique
          - not_null